### ISSUE TITLE
Some work required for production quality

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/services-template-helm#9]
When I helped @GDYendell update an old beamline repo to this template yesterday I felt that there were still quite a few issues here:

- the CI is not working: we probably need to just suck up the fact that we need to get the gitlab K8S CI working. Although I'd love to pursue virtual machines for CI - that is also lots of work and may be far off. It occurs to me that we could use python kubernetes library to drive the pod creation instead of kubectl in a script.
- There are too many copier template questions and I was not entirely clear on all the answers. Review how these could be reduced and perhaps clean up the descriptions. In particular:
  - location: we should drop the blxxi form for this and make it the same as everything else: ixx
  - location: we should not even ask about this for beamlines - just use the beamline short name (first question)
  - in general a separation between accelerator and beamline Qs may be useful?
- the example IOC looks wrong because of its prefix (yes this was my choice) I think we should drop the example ioc as we now have the .ioc-template folder @marcelldls I think maybe you are a fan of the example - let me know your thoughts?

@GDYendell does anything else come to mind?

REMINDER: the tutorials will need updating to reflect any changes here.

**Comment by marcelldls** [comment]
> When I helped @GDYendell update an old beamline repo to this template yesterday I felt that there were still quite a few issues here:

- @gilesknap is another idea to have a "epics containers" CI container which includes all our dependencies? This could run from podman or be the container launched by the runner?
- How will you know its a beamline? (I hope the answer is not the desire to include beamline specific logic. My personal feeling is that we should not include such constructs and rather remain abstract)
- A good reason for the example IOC is that we can use it as a canary rather than messing with in production IOCs

**Comment by marcelldls** [comment]
> Would it make sense to move DLS technical area earlier to infer some of the other answers?
DLS technical area follows the decision that you are using `gitlab.diamond.ac.uk` as your repo. Therefore we can add diamond specific logic like the idea of a "beamline". Im not for the idea that there is accellerator and beamline logic, why can we not rather remain consistent?

**Comment by GDYendell** [comment]
Ah OK, so the DLS technical area it is only used to determine GitLab repo. So, should the description and cluster namespace not default to beamline if we want to keep it more generic?

**Comment by marcelldls** [comment]
> Ah OK, so the DLS technical area it is only used to determine GitLab repo. So, should the description and cluster namespace not default to beamline if we want to keep it more generic?

At the moment there is no default which I think is good. There are hints though? We could put that as beamline. I think we should probably remove it because its confusing.

I think there is merit in reordering the questions so that the logic flows better. From
```
- ioc_group
- description
- cluster_namespace
- cluster_name
- cluster_type
- location
- git_platform
- dls_technical_area
- repo_uri
- logging_url
```
To 
```
- ioc_group
- description
- location
- cluster_name
- cluster_namespace
- cluster_type
- git_platform
- dls_technical_area
- repo_uri
- logging_url
```

**Comment by gilesknap** [comment]
@GDYendell @marcelldls I have make a PR #10 with some suggestions that I think makes it clearer.

I have made 2 PRs for easier diff examination
- rewording
- re-ordering and formatting (added multi-line questions as copier truncates wide questions)
